import { Command } from "commander";
import chalk from "chalk";
import { existsSync, readFileSync, writeFileSync, rmSync } from "fs";
import { resolve, join } from "path";
import { homedir } from "os";
import { tryResolveAgent } from "../lib/require-agent.js";
import { AGENT_DIR } from "../config/store.js";
import { signJwt } from "../lib/jwt.js";

const CLAUDE_START = "<!-- agentvalet:start -->";
const CLAUDE_END   = "<!-- agentvalet:end -->";
const PERMISSIONS_START = "<!-- agentvalet:permissions:start -->";
const PERMISSIONS_END   = "<!-- agentvalet:permissions:end -->";
const HOOK_MARKER  = "agentvalet/register refresh";

function stripPermissionsBlock(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  try {
    const content = readFileSync(filePath, "utf-8");
    if (!content.includes(PERMISSIONS_START)) return false;
    const stripped = content
      .replace(new RegExp(`${PERMISSIONS_START}[\\s\\S]*?${PERMISSIONS_END}`, "m"), "")
      .replace(/(\r?\n){3,}/g, "\n\n")
      .trimEnd();
    writeFileSync(filePath, stripped + "\n", "utf-8");
    return true;
  } catch { return false; }
}


function stripClaudeMd(): void {
  const path = resolve("CLAUDE.md");
  if (!existsSync(path)) return;
  let content = readFileSync(path, "utf-8");
  content = content.replace(new RegExp(`${CLAUDE_START}[\\s\\S]*?${CLAUDE_END}`, "m"), "");
  content = content.replace(/^@\.claude\/agentvalet-permissions\.md\s*$/m, "");
  content = content.replace(/(\r?\n){3,}/g, "\n\n").trim();
  writeFileSync(path, content ? content + "\n" : "", "utf-8");
}

function stripSettingsJson(): void {
  const path = resolve(".claude/settings.local.json");
  if (!existsSync(path)) return;
  try {
    const settings = JSON.parse(readFileSync(path, "utf-8")) as Record<string, unknown>;
    const hooks = (settings.hooks ?? {}) as Record<string, unknown>;
    const ups = (hooks.UserPromptSubmit ?? []) as Array<{ hooks?: Array<{ command?: string }> }>;
    hooks.UserPromptSubmit = ups.filter(
      (e) => !e.hooks?.some((h) => h.command?.includes(HOOK_MARKER))
    );
    settings.hooks = hooks;
    const perms = (settings.permissions ?? {}) as Record<string, unknown>;
    const allow = (perms.allow ?? []) as string[];
    perms.allow = allow.filter((e) => !e.startsWith("mcp__agentvalet__"));
    settings.permissions = perms;
    writeFileSync(path, JSON.stringify(settings, null, 2) + "\n", "utf-8");
  } catch { /* leave file alone if unparseable */ }
}

function stripMcpJson(filePath: string, options: { wrapped?: boolean } = {}): boolean {
  if (!existsSync(filePath)) return false;
  try {
    const config = JSON.parse(readFileSync(filePath, "utf-8")) as Record<string, unknown>;
    let removed = false;
    if (options.wrapped === false) {
      // Flat structure (Factory Droid: top-level keys are server names)
      if (config["agentvalet"] !== undefined) {
        delete config["agentvalet"];
        removed = true;
      }
    } else {
      // Wrapped: { mcpServers: { agentvalet: {...} } }
      const servers = (config.mcpServers ?? {}) as Record<string, unknown>;
      if (servers["agentvalet"] !== undefined) {
        delete servers["agentvalet"];
        config.mcpServers = servers;
        removed = true;
      }
    }
    if (removed) {
      writeFileSync(filePath, JSON.stringify(config, null, 2) + "\n", "utf-8");
    }
    return removed;
  } catch { return false; }
}

function stripCodexTomlAt(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  try {
    const content = readFileSync(filePath, "utf-8");
    // Remove the [mcp_servers.agentvalet] block (header line + following lines
    // until blank line or next header). Conservative: only strip if marker present.
    if (!content.includes("[mcp_servers.agentvalet]")) return false;
    const stripped = content.replace(
      /\r?\n?\[mcp_servers\.agentvalet\][\s\S]*?(?=\r?\n\[|\r?\n*$)/,
      ""
    );
    writeFileSync(filePath, stripped.replace(/(\r?\n){3,}/g, "\n\n").trimEnd() + "\n", "utf-8");
    return true;
  } catch { return false; }
}

// Returns true if the file's first non-empty line matches one of the markers
// — i.e. the file was generated by us and is safe to delete.
function isAgentValetGeneratedDoc(filePath: string, markers: string[]): boolean {
  if (!existsSync(filePath)) return false;
  try {
    const content = readFileSync(filePath, "utf-8");
    const firstLine = content.split(/\r?\n/).find((l) => l.trim().length > 0) ?? "";
    return markers.some((m) => firstLine.startsWith(m));
  } catch { return false; }
}

export function cleanLocally(): void {
  const removed: string[] = [];
  const stripped: string[] = [];
  const r = (p: string) => { const abs = resolve(p); if (existsSync(abs)) { rmSync(abs, { recursive: true, force: true }); removed.push(abs); } };
  const rAbs = (abs: string) => { if (existsSync(abs)) { rmSync(abs, { recursive: true, force: true }); removed.push(abs); } };

  // Machine-level identity — remove the entire ~/.agentvalet directory
  // (agent.key + config.json + anything else AgentValet writes there)
  rAbs(AGENT_DIR);

  // Legacy project-level files
  r(".env.agentvalet");
  r(".agentvalet");
  r("agentvalet.key");
  r(".claude/agentvalet-permissions.md");

  // Pure-AgentValet files: always safe to delete
  r("AGENTVALET.md");
  r(".factory/droids/agentvalet.yaml");
  r(".factory/droids/agentvalet-reliability.yaml");
  r(".factory/commands/av-status.md");
  r(".factory/commands/av-register.md");

  // Generated docs: only delete if first line matches our marker (don't clobber
  // user-edited content that happens to share the filename)
  const agentsMd = resolve("AGENTS.md");
  if (isAgentValetGeneratedDoc(agentsMd, ["# AgentValet"])) rAbs(agentsMd);
  const skillMd = resolve("SKILL.md");
  if (isAgentValetGeneratedDoc(skillMd, ["# AgentValet"])) rAbs(skillMd);

  // MCP config files: strip the agentvalet entry, do NOT delete the file.
  // Cleans BOTH project-scoped and user-scoped entries — uninstall removes
  // the agent regardless of which scope the install used.
  // Project-scoped:
  if (stripMcpJson(resolve(".mcp.json"))) stripped.push(".mcp.json");
  if (stripMcpJson(resolve(".cursor/mcp.json"))) stripped.push(".cursor/mcp.json");
  if (stripMcpJson(resolve(".factory/mcp.json"), { wrapped: false })) stripped.push(".factory/mcp.json");
  // User-scoped:
  const home = homedir();
  if (stripMcpJson(join(home, ".claude.json"))) stripped.push("~/.claude.json");
  if (stripMcpJson(join(home, ".cursor", "mcp.json"))) stripped.push("~/.cursor/mcp.json");
  if (stripMcpJson(join(home, ".factory", "mcp.json"), { wrapped: false })) stripped.push("~/.factory/mcp.json");
  if (stripCodexTomlAt(join(home, ".codex", "config.toml"))) stripped.push("~/.codex/config.toml");
  // Project-scoped Codex (covers CLI, IDE extension, Desktop app on trusted projects)
  if (stripCodexTomlAt(resolve(".codex/config.toml"))) stripped.push(".codex/config.toml");

  // CLAUDE.md and Claude Code settings.local.json — strip agentvalet sections
  stripClaudeMd();
  stripSettingsJson();
  stripped.push("CLAUDE.md", ".claude/settings.local.json");

  // Strip framework-neutral permissions blocks from Codex AGENTS.md and
  // OpenClaw SKILL.md (written by `refresh` for non-Claude frameworks).
  if (stripPermissionsBlock(resolve("AGENTS.md"))) stripped.push("AGENTS.md");
  if (stripPermissionsBlock(resolve("SKILL.md"))) stripped.push("SKILL.md");

  if (removed.length > 0) {
    console.log(chalk.green("  ✓ Removed files:"));
    for (const f of removed) console.log(chalk.dim(`      ${f}`));
  }
  if (stripped.length > 0) {
    console.log(chalk.green("  ✓ Stripped agentvalet entries from:"));
    for (const f of stripped) console.log(chalk.dim(`      ${f}`));
  }
}

const SSE_READ_TIMEOUT_MS = 25_000; // reconnect if no data received in 25s

async function pollForApproval(apiUrl: string, revocationToken: string, timeoutMs: number): Promise<"approved" | "rejected" | "timeout"> {
  const streamUrl = `${apiUrl}/v1/revoke-request/stream/${revocationToken}`;
  const deadline = Date.now() + timeoutMs;

  return new Promise((resolve) => {
    let settled = false;

    function done(result: "approved" | "rejected" | "timeout") {
      if (!settled) { settled = true; resolve(result); }
    }

    function connect() {
      if (settled || Date.now() > deadline) { done("timeout"); return; }

      const controller = new AbortController();
      // Abort the fetch if no data arrives within SSE_READ_TIMEOUT_MS
      let readTimer = setTimeout(() => controller.abort(), SSE_READ_TIMEOUT_MS);

      function resetReadTimer() {
        clearTimeout(readTimer);
        readTimer = setTimeout(() => controller.abort(), SSE_READ_TIMEOUT_MS);
      }

      fetch(streamUrl, { signal: controller.signal, headers: { Accept: "text/event-stream" } })
        .then(async (res) => {
          if (!res.ok || !res.body) {
            clearTimeout(readTimer);
            // Non-2xx — back off and retry instead of giving up
            if (!settled) setTimeout(connect, 3000);
            return;
          }
          const reader = res.body.getReader();
          const decoder = new TextDecoder();
          let buf = "";
          try {
            while (true) {
              const { done: streamDone, value } = await reader.read();
              resetReadTimer();
              if (streamDone) break;
              buf += decoder.decode(value, { stream: true });
              const lines = buf.split("\n");
              buf = lines.pop() ?? "";
              for (const line of lines) {
                if (line.startsWith(":")) continue; // heartbeat — keep alive
                if (!line.startsWith("data: ")) continue;
                try {
                  const evt = JSON.parse(line.slice(6)) as { status: string };
                  if (evt.status === "approved") { clearTimeout(readTimer); done("approved"); return; }
                  if (evt.status === "rejected") { clearTimeout(readTimer); done("rejected"); return; }
                  if (evt.status === "timeout")  { clearTimeout(readTimer); done("timeout");  return; }
                } catch { /* bad JSON — ignore */ }
              }
            }
          } finally {
            clearTimeout(readTimer);
          }
          // Stream closed without resolution — reconnect after short delay
          if (!settled) setTimeout(connect, 1000);
        })
        .catch(() => {
          clearTimeout(readTimer);
          // Aborted (read timeout) or network error — reconnect
          if (!settled) setTimeout(connect, 1000);
        });
    }

    connect();
    setTimeout(() => done("timeout"), timeoutMs);
  });
}

export function uninstallCommand(): Command {
  return new Command("uninstall")
    .description("Request agent revocation (requires owner approval) and remove all local files")
    .option("--local-only", "Skip the server-side revoke request — just clean local files")
    .option("--timeout <seconds>", "Seconds to wait for owner approval", "300")
    .action(async (opts) => {
      const timeoutMs = parseInt(opts.timeout as string, 10) * 1000;
      const creds = tryResolveAgent();

      if (opts.localOnly || !creds) {
        if (!creds) console.log(chalk.dim("  No agent credentials found — cleaning local files only."));
        cleanLocally();
        console.log(chalk.dim("\n  To register a new agent: npx @agentvalet/register"));
        return;
      }

      let privateKeyPem: string | undefined;
      try { privateKeyPem = readFileSync(creds.keyPath, "utf-8").trim(); } catch { /* missing */ }

      if (!privateKeyPem) {
        console.log(chalk.yellow("  ⚠ Private key not found — cannot submit revocation request."));
        console.log(chalk.dim("  Use --local-only to clean local files without revoking."));
        process.exit(1);
      }

      // ── Submit revocation request ────────────────────────────────────────
      console.log(chalk.dim(`\n  Submitting revocation request for ${creds.agentId}...`));
      const jwt = signJwt(creds.agentId, creds.ownerId, privateKeyPem);

      let revocationToken: string;
      try {
        const res = await fetch(`${creds.apiUrl}/v1/revoke-request`, {
          method: "POST",
          headers: { Authorization: `Bearer ${jwt}`, "Content-Type": "application/json" },
          body: JSON.stringify({ reason: "CLI uninstall" }),
        });
        const body = await res.json() as { revocation_token?: string; error?: string };
        if (res.status === 404 || res.status === 409) {
          // Agent already revoked or not found on server — clean up locally
          console.log(chalk.yellow(`  ⚠ Agent not found on server (already revoked?) — cleaning local files.`));
          cleanLocally();
          console.log(chalk.dim("\n  To register a new agent: npx @agentvalet/register"));
          return;
        }
        if (!res.ok || !body.revocation_token) {
          throw new Error(body.error ?? `HTTP ${res.status}`);
        }
        revocationToken = body.revocation_token;
      } catch (err) {
        console.error(chalk.red(`  ✗ Failed to submit revocation request: ${err instanceof Error ? err.message : err}`));
        process.exit(1);
      }

      console.log(chalk.green("  ✓ Revocation request submitted"));
      console.log("");
      console.log(chalk.yellow("  ACTION REQUIRED:"));
      console.log(chalk.yellow(`  Open ${creds.apiUrl.replace("api.", "app.")}/agents and approve the uninstall request.`));
      console.log(chalk.dim(`  Waiting up to ${opts.timeout}s for approval...\n`));

      // ── Poll SSE for owner decision ──────────────────────────────────────
      const result = await pollForApproval(creds.apiUrl, revocationToken, timeoutMs);

      if (result === "rejected") {
        console.log(chalk.red("\n  ✗ Owner rejected the uninstall request. Agent remains active."));
        process.exit(1);
      }

      if (result === "timeout") {
        console.log(chalk.yellow("\n  ⚠ Timed out waiting for owner approval."));
        console.log(chalk.dim("  The request remains pending in your dashboard. Run again to resume."));
        process.exit(1);
      }

      // ── Approved — clean local files ─────────────────────────────────────
      console.log(chalk.green("\n  ✓ Approved — cleaning local files...\n"));
      cleanLocally();
      console.log("");
      console.log(chalk.dim("  Agent revoked. To register a new agent: npx @agentvalet/register"));
    });
}
